"""add img url

Revision ID: 39f56d01e374
Revises: e829c8e46b47
Create Date: 2016-12-04 17:19:36.851566

"""

# revision identifiers, used by Alembic.
revision = '39f56d01e374'
down_revision = 'e829c8e46b47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('img_url_postfix', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'img_url_postfix')
    ### end Alembic commands ###
