"""add model Role

Revision ID: 49f2d1c20971
Revises: 4429e2e95413
Create Date: 2016-11-24 21:29:37.175554

"""

# revision identifiers, used by Alembic.
revision = '49f2d1c20971'
down_revision = '4429e2e95413'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'users', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column(u'users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    op.drop_index('nickname', table_name='users')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index('nickname', 'users', ['nickname'], unique=True)
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column(u'users', 'role_id')
    op.drop_column(u'users', 'email')
    op.drop_table('roles')
    ### end Alembic commands ###
