"""add body_html

Revision ID: 9f30e205c308
Revises: 7477440eda65
Create Date: 2016-12-02 15:59:41.671144

"""

# revision identifiers, used by Alembic.
revision = '9f30e205c308'
down_revision = '7477440eda65'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
